### ISSUE TITLE
关于plac-knn-mt运行报错

### ISSUE THREAD

**Issue by Asomey** [NJUNLP/knn-box#10]
你好，我们在进行运行plac-knn-mt的时候
首先bash save_mt_pred.sh，
接着bash save_drop_index.sh，
然后bash prune_datastore.sh对datastore进行prune后，
使用vanilla-knn-mt中的inference，能够正常运行，但是运行出来的BLUE是0。
![微信图片_20221223222547](https://user-images.githubusercontent.com/61071895/209351661-ef759e29-579c-4596-86aa-a67dfd0916c5.jpg)

**Comment by Maxwell-Lyu** [comment]
是否方便提供一下您实际运行的脚本内容，每个脚本的输出，以及您的datastore这个目录下面最终的文件有哪些？
+ 您的运行步骤基本是正确的
  + PLAC从通用MT模型和领域内数据出发，保存mt_preds，即模型的预测结果，还有key和val。这里需要特别注意，plac-knn-mt **不能** 进行inference
  + 用预测结果和val，可以计算出模型是否做对，即mt_known，并用key进行KNN检索，得到drop_index
  + PLAC是用来裁剪一个 **已有** 的datastore的，所以除了需要drop_index，还需要与其对应的一个普通datastore（必须要有key！）才能创建新的、裁减过的datastore
  + PLAC会顺便为新的datastore创建faiss_index
