### ISSUE TITLE
基础NMT模型fairseq版本冲突问题

### ISSUE THREAD

**Issue by sammichenVV** [NJUNLP/knn-box#18]
hello，我在用您的代码运行vanilla-knn-mt/build_datastore.sh遇到了这个错误。我的基础NMT模型fairseq版本是最新的V0.12训练的。在加载模型参数的时候报了这个错误:
AttributeError: 'NoneType' object has no attribute 'user_dir'
![Uploading image.png…]
这个错误是因为fairseq新版本已经没有用  state["args"]，已经改成了state['cfgs']。

![image](https://user-images.githubusercontent.com/22388079/219536245-92a6324c-2588-43cf-beec-e1ec316eddb3.png)
当我把代码改成state[‘cfgs’]时，报错：
![image](https://user-images.githubusercontent.com/22388079/219536538-65c47ed4-ecdf-4a3c-a3a4-95320ed3352d.png)
0.10的state["args"]是argparse.Namespace类型
![image](https://user-images.githubusercontent.com/22388079/219536849-d4591403-b2cf-43f3-a0ce-349196fdc92b.png)
如果要改代码好像要改许多地方，这也是我发现的其中一个版本不一致带来的问题，应该之后还会有类似的问题。貌似对新版本的fairseq训练的模型不太友好，有比较好的解决方式么？谢谢

**Comment by Maxwell-Lyu** [comment]
感谢您指出这个问题。我们经过对checkpoint文件的对比，确认了您提出的现象，您可以按照下面的示例代码，对checkpoint进行一个小的修改，以正常加载，而kNN-BOX的代码无需修改：
``` python
import torch
new_version_ckpt = torch.load("<新版本保存的checkpoint路径>")
new_version_ckpt["args"] = new_version_ckpt["cfg"]["model"]
torch.save(new_version_ckpt, "<为旧版本转换过的checkpiont>")
```
尖括号内的文件名请按需填写，以下是一些补充说明：
新版本中，fairseq会向checkpoint里面保存更多的配置信息，而原本的`ckpt["args"]`仅包含模型的信息，改保存到`ckpt["cfg"]["model"]`中，类型仍为`argparseNamespace`

**Comment by sammichenVV** [comment]
> 谢谢!我转换以后又有了新的报错
![image](https://user-images.githubusercontent.com/22388079/219939113-7c3e736f-6e09-4f70-9a04-566ef5abb9c1.png)

**Comment by Maxwell-Lyu** [comment]
这个报错的根本原因，是在于模型训练时的dict和当前你提供的dict大小不一致。
checkpoint中的tensor长度是32103，这是直接从checkpoint里面加载出来的；而fairseq加载模型时，是先创建一个空模型，再从checkpoint里面逐个加载同名参数的tensor，这个空模型的tensor长度是由词表计算出来的，你可以看一下dict.??.txt文件的行数，我想应该差不多是32000左右，可能会少4行这样。

这个问题的解决方案取决于您是否使用了正确的dict文件，我没有遇到过这么大的差值（102），所以请您告知一下具体是在用什么模型，这个模型是否为多语言或者预训练语言模型，另外最好是让我看一下dict文件的开头、末尾各10行，我判断一下dict文件的状态

**Comment by sammichenVV** [comment]
感谢！我检查了下词表，确实是词典少了，基础模型训练是用task任务"mutil_simple_epoch"来训练的多垂域，训练时会自动把参数lang_dict的词典加到词表里，总之换了个非垂域模型跑通了，之后想做多语模型的KNNMT扩展，如果能够支持mutil_simple_epoch的任务就更好啦

**Comment by Maxwell-Lyu** [comment]
我们已经试验过M2M100，一个多对多预训练翻译模型，正是使用translation_mutil_simple_epoch训练的，kNN的运行结果比较正常，能够在模型的基础上得到一些BLEU提升。
M2M100的官方repo，提供了2个dict：

|Size|Name|
|-|-|
|128000|data_dict.128k.txt|
|128108|model_dict.128k.txt|

我认为您可以效仿他们的做法，手动准备另一个添加过lang_dict的词典，用于其他的实验任务。这是我在M2M100上实验时的脚本，供您参考。您可能需要特别注意`--fixed-dictionary`参数的作用
```
# build_datastore
CUDA_VISIBLE_DEVICES=$1 python $PROJECT_PATH/../common/validate.py $DATA_PATH \
  --task translation_multi_simple_epoch \
  --lang-pairs $PROJECT_PATH/model/language_pairs_small_models.txt \
  --fixed-dictionary $PROJECT_PATH/model/model_dict.128k.txt \
  --decoder-langtok --encoder-langtok src \
  --model-overrides "{'eval_bleu': False, 'required_seq_len_multiple':1, 'load_alignments': False}" \
  --path $BASE_MODEL \
  -s $SRC -t $TGT \
  --dataset-impl mmap \
  --valid-subset $DOMAIN.train \
  --skip-invalid-size-inputs-valid-test \
  --max-tokens 4096 \
  --bpe fastbpe \
  --user-dir $PROJECT_PATH/../../knnbox/models \
  --arch adaptive_knn_mt@transformer_wmt_en_de_big \
  --knn-mode build_datastore \
  --knn-datastore-path  $DATASTORE_SAVE_PATH \
```
``` 
# vanilla_knn_inference
CUDA_VISIBLE_DEVICES=$1 python $PROJECT_PATH/../common/generate.py $DATA_PATH \
--task translation_multi_simple_epoch \
--lang-pairs $PROJECT_PATH/model/language_pairs_small_models.txt \
--fixed-dictionary $PROJECT_PATH/model/model_dict.128k.txt \
--source-lang $SRC --target-lang $TGT \
--encoder-normalize-before \
--decoder-normalize-before \
--dropout 0.3 \
--attention-dropout 0.1 \
--encoder-layers 12 \
--decoder-layers 12 \
--encoder-layerdrop 0.05 \
--decoder-layerdrop 0.05 \
--share-decoder-input-output-embed \
--share-all-embeddings \
--encoder-langtok src \
--decoder-langtok \
--path $BASE_MODEL \
--dataset-impl mmap \
--beam 5 \
--gen-subset $DOMAIN.$SUBSET \
--model-overrides "{'eval_bleu': False, 'required_seq_len_multiple':1, 'load_alignments': False}" \
--max-tokens 1024 \
--remove-bpe sentencepiece \
--scoring sacrebleu \
--arch robust_knn_mt@transformer_wmt_en_de_big \
--user-dir $PROJECT_PATH/../../knnbox/models \
--knn-mode inference \
--knn-datastore-path  $DATASTORE_LOAD_PATH \
--knn-max-k $MAX_K \
--knn-combiner-path $COMBINER_LOAD_DIR > $PROJECT_PATH/out/$DOMAIN.$SUBSET.$LANG.$DSTORE_LANG.$PARAM.txt
```

**Comment by sammichenVV** [comment]
好的，感谢

**Comment by sammichenVV** [comment]
hello,我在运行vanilla-knn-mt推理时inference跑出来的bleu值只有1.68，我不知道是哪里出了问题
![image](https://user-images.githubusercontent.com/22388079/220841431-86d671b1-e92d-45aa-814c-cff55aebd1b3.png)
这个是基础模型的结果：
![image](https://user-images.githubusercontent.com/22388079/220841563-46522112-9494-4ccb-8baa-e1b8ed2fbbaa.png)
build_datastore代码及运行结果:
![image](https://user-images.githubusercontent.com/22388079/220850425-632985dd-31e0-4c5d-9fbc-7ca27a5475f0.png)
![image](https://user-images.githubusercontent.com/22388079/220850780-1056a604-5e77-481a-9672-fc0c6e3eee55.png)
inference.sh代码及运行结果:
![image](https://user-images.githubusercontent.com/22388079/220859518-8c2e55f9-5a48-4a7f-baff-f222fdf0d44b.png)

**Comment by Maxwell-Lyu** [comment]
您昨天说了基础模型是mutil_simple_epoch训练出来的，但是您提供的脚本里面，task为什么设置的是一般的translation呢？

**Comment by sammichenVV** [comment]
因为我换了个用translation训练的模型

**Comment by sammichenVV** [comment]
您的代码我只修改了这里，因为与基础模型不匹配，应该不是这个原因导致的吧
![image](https://user-images.githubusercontent.com/22388079/220862398-203af4a4-9bab-44bc-bae5-90e761cb823b.png)

**Comment by Maxwell-Lyu** [comment]
我已经被绕晕了，我想想

**Comment by Maxwell-Lyu** [comment]
基础模型的结果，请问您用于生成的脚本可以给我看一下吗

**Comment by sammichenVV** [comment]
额，不好意思把你绕晕了，我之前提到的mutil_simple_epoch是另一个模型（当时以为knnbox不支持）所以我换了一个基于translation训练的模型，也就是现在报错这个

**Comment by sammichenVV** [comment]
这个是基础模型生成翻译脚本：
![image](https://user-images.githubusercontent.com/22388079/220864377-18334448-49d2-4233-88ea-a7e1e316c313.png)

**Comment by Maxwell-Lyu** [comment]
我仔细对比了几个脚本，并没有发现可疑的地方。从我的经验来看，以下问题应该可以排除
+ 模型结构问题：如果模型的结构（维度、层数）真的不匹配，fairseq应该会报错
+ 数据、checkpoint、datastore路径问题：会报错

我目前无法得知，有可能导致问题的配置：    
+ 模型其他参数：transformer模型还有其他许多非数值配置，例如share_decoder_input_output_embed等，请仔细核对base模型训练时候的脚本，将特殊的模型参数全部给设置好
+ 核查这个问题所需的信息，是几个输出结果**最前面**，由Namespace开头的，模型参数信息。如果你注意到这里面，类型为bool的某个参数不同，那么很有可能是这个参数不匹配。例如基础模型的某个是True，而build_datastore的对应是False
+ 你也可以将knn的lambda强制调整为0.0001（为了保证稳定，不要改成0），这样可以屏蔽kNN的概率分布，只看base模型结果。如果此时BLEU非常接近基础模型结果，则说明是build_datastore时候，缺少了某些参数，导致knn-box没有正确推断出模型的一些配置信息，提取的隐层表示无意义

**Comment by sammichenVV** [comment]
谢谢，我把lambda改成0.0001，bleu结果更低了！
![image](https://user-images.githubusercontent.com/22388079/220871723-fe61dcb2-175b-4e49-9da2-1974c7785473.png)

**Comment by Maxwell-Lyu** [comment]
这个结果意味着，knn部分不是问题的根源，问题出在模型的参数设置上，请检查训练脚本，看看是否在transformer模型的基础上做了一些配置

**Comment by ZhaoQianfeng** [comment]
你可以看看执行base-nmt inference的时候打印出来的args，那个是从checkpoint里拿出来的。然后对比下knn inference时打印的args看是否一致。有一些重要的参数比方说share_decoder_input_output_embed，encoder-normalize-before，decoder-normalize-before都会影响模型的行为，要确保执行build_datastore inference脚本时指定的arch和预训练模型训练时的arch是匹配的。

**Comment by sammichenVV** [comment]
好的 加了模型参数确实结果好了，谢谢
