### ISSUE TITLE
关于vanilla-knn-mt inference报错

### ISSUE THREAD

**Issue by 17freeman** [NJUNLP/knn-box#21]
![image](https://user-images.githubusercontent.com/42693096/222062282-175f14a9-2ce0-409a-a3ce-e96d94d14281.png)
[](url)

在inference时，频频出现此类AttributeError: 'Namespace' object has no attribute 的错误。

还有就是，无法调用父类文件knnbox，ModuleNotFoundError: No module named 'knnbox'

**Comment by ZhaoQianfeng** [comment]
@17freeman 你好，从报错信息来看，这个conda环境似乎曾经安装了一个其他版本的fairseq，使得knn-box代码中对fairseq的引用都指向了以前那个版本的fairseq，但新旧版本的fairseq并不兼容。你可以通过重新开一个环境安装knn-box来解决这个问题，希望对你有帮助。
![屏幕截图 2023-03-02 231619](https://user-images.githubusercontent.com/53401404/222470075-04cd1c5d-605a-427f-9f07-ba0d9cd7e5f8.png)
