### ISSUE TITLE
关于RuntimeError: Error(s) in loading state_dict for VanillaKNNMT:

### ISSUE THREAD

**Issue by txz201603604** [NJUNLP/knn-box#28]
您好，我在运行vanilla-knn-mt/inference.sh脚本后，在加载模型时出现了错误：
![53BEE0C2-6E30-4acd-8C00-A5DE6FC55474](https://github.com/NJUNLP/knn-box/assets/43235349/8e8ebc6a-3519-470f-9c0e-e487df703a63)
这是我的运行脚本：
![image](https://github.com/NJUNLP/knn-box/assets/43235349/60423294-455b-4dac-bd94-4a0399aa02a8)
请问这个问题应该如何解决？

**Comment by sxysxy** [comment]
看起来你修改了原本infernece.sh内的参数，比如BASE_MODEL和--arch。你需要检查你的checkpoint文件存储的模型，是否能和--arch指定的模型的结构对应上
