### ISSUE TITLE
Multi-processing for huge datastore

### ISSUE THREAD

**Issue by Jong-Won** [NJUNLP/knn-box#3]
Thanks for sharing the great tool.

I am wondering if the tool supports multi-processing when saving keys and value to datastore (i.e. multi-gpu inference and saving key values). It may helps for huge datastore application.

**Comment by ZhaoQianfeng** [comment]
Sorry, this toolkit  does not support multi-GPU currently. It is a good suggestion, maybe we will consider supporting this feature in the future.

**Comment by Jong-Won** [comment]
Thanks for your clarification!
