### ISSUE TITLE
运行adaptive knn-mt出错

### ISSUE THREAD

**Issue by Asomey** [NJUNLP/knn-box#6]
你好，我想请教一个问题。
我在运行adaptive knn-mt中的 bash train_metak.sh的时候。
运行结果报错如下：
RuntimeError: Error in faiss::gpu::GpuIndex::GpuIndex(std::shared_ptr<faiss::gpu::GpuResources>, int, faiss::MetricType, float, faiss::gpu::GpuIndexConfig) at /root/miniconda3/conda-bld/faiss-pkg_1669821591485/work/faiss/gpu/GpuIndex.cu:58: Error: 'config_.device < getNumDevices()' failed: Invalid GPU device 0
感觉像是GPU未能识别，但是查了下nvidia-smi都是能看到GPU序号是0和1的。
而且在跑vanilla knn-mt时程序都是好的。

**Comment by Old-Young233** [comment]
![image](https://user-images.githubusercontent.com/33386155/206841002-4f857ab1-aa5a-44fb-acc1-590f287ae452.png)
是不是这个地方没修改

**Comment by Asomey** [comment]
十分感谢大佬！效率太高了！问题已解决！
